// extaudit - Markdown report generator
import type { ExtensionRisk, ReportSummary } from "../types.js";

/**
 * Generate a human-readable Markdown audit report.
 */
export function generateMarkdownReport(args: {
  version: string;
  scannedDirectories: string[];
  extensions: ExtensionRisk[];
  appliedRules: string[];
  summary: ReportSummary;
}): string {
  const lines: string[] = [];

  lines.push("# extaudit Security Report");
  lines.push("");
  lines.push(`**Generated:** ${new Date().toISOString()}`);
  lines.push(`**Version:** ${args.version}`);
  lines.push(`**Directories scanned:** ${args.scannedDirectories.join(", ") || "none (no extensions found)"}`);
  lines.push(`**Extensions analyzed:** ${args.extensions.length}`);
  lines.push("");

  // Summary section
  lines.push("## Summary");
  lines.push("");
  lines.push(`| Severity | Count |`);
  lines.push(`|----------|------:|`);
  lines.push(`| Critical | ${args.summary.critical} |`);
  lines.push(`| High     | ${args.summary.high} |`);
  lines.push(`| Medium   | ${args.summary.medium} |`);
  lines.push(`| Low      | ${args.summary.low} |`);
  lines.push(`| Info     | ${args.summary.info} |`);
  lines.push("");
  lines.push(`**Max risk score:** ${args.summary.maxScore}/100`);
  lines.push(`**Average risk score:** ${args.summary.averageScore}/100`);
  lines.push("");

  // Per-extension findings
  if (args.extensions.length > 0) {
    lines.push("## Extension Findings");
    lines.push("");

    for (const ext of args.extensions) {
      lines.push(`### ${ext.extensionName}`);
      lines.push("");
      lines.push(`- **Path:** \`${ext.extensionPath}\``);
      lines.push(`- **Risk score:** ${ext.score}/100 (${ext.label})`);
      lines.push("");

      if (ext.findings.length > 0) {
        lines.push("**Findings:**");
        lines.push("");
        for (const f of ext.findings) {
          lines.push(`- **[${f.severity.toUpperCase()}]** ${f.description}`);
          for (const e of f.evidence) {
            lines.push(`  - ${e}`);
          }
        }
      } else {
        lines.push("*No findings - extension appears clean*");
      }
      lines.push("");
    }
  } else {
    lines.push("No extensions found to audit.");
    lines.push("");
  }

  // Rules applied
  lines.push("## Applied Rules");
  lines.push("");
  for (const ruleId of args.appliedRules) {
    lines.push(`- ${ruleId}`);
  }
  lines.push("");
  lines.push("---");
  lines.push("*Report generated by extaudit*");

  return lines.join("\n");
}
