import {
  ExtensionManifest, ExtensionScore, AuditReport,
  Severity, RiskRule, SEVERITY_WEIGHTS, CliConfig, Finding,
} from "./types.js"
import { DEFAULT_RULES, loadCustomRules } from "./rules.js"
import { discoverExtensions, parseManifest } from "./manifest.js"

const T = { caution: 10, suspicious: 25, dangerous: 50 }

export function scoreExtension(
  manifest: ExtensionManifest,
  rules: RiskRule[] = DEFAULT_RULES,
  minSeverity: Severity = "low",
): ExtensionScore {
  const order: Severity[] = ["low","medium","high","critical"]
  const minIdx = order.indexOf(minSeverity)
  const findings: Finding[] = []
  for (const r of rules) {
    const f = r.check(manifest)
    if (f && order.indexOf(f.severity) >= minIdx) findings.push(f)
  }
  const score = findings.reduce((s, f) => s + SEVERITY_WEIGHTS[f.severity], 0)
  return { manifest, score, riskLevel: getRiskLevel(score), findings }
}

export function getRiskLevel(score: number): ExtensionScore["riskLevel"] {
  if (score >= T.dangerous) return "dangerous"
  if (score >= T.suspicious) return "suspicious"
  if (score >= T.caution) return "caution"
  return "safe"
}

export function scan(config: CliConfig): AuditReport {
  const errors: string[] = []
  const extensions: ExtensionScore[] = []
  const discovered = discoverExtensions(config.scanPaths)
  const rules = config.customRulesPath ? loadCustomRules(config.customRulesPath) : DEFAULT_RULES

  for (const ext of discovered) {
    try {
      const m = parseManifest(ext.packageJson, ext.directory)
      extensions.push(scoreExtension(m, rules, config.minSeverity))
    } catch (err) {
      errors.push(`Failed to parse ${ext.packageJson}: ${err}`)
    }
  }

  const sev: Record<Severity,number> = { low:0, medium:0, high:0, critical:0 }
  let totalFindings = 0, totalScore = 0
  for (const e of extensions) {
    totalFindings += e.findings.length
    totalScore += e.score
    for (const f of e.findings) sev[f.severity]++
  }
  extensions.sort((a, b) => b.score - a.score)
  const avg = extensions.length > 0 ? Math.round(totalScore / extensions.length) : 0

  return {
    timestamp: new Date().toISOString(),
    target: config.scanPaths.join(", "),
    extensionsScanned: extensions.length,
    extensionsFailed: errors.length,
    totalFindings, severityCounts: sev,
    overallScore: totalScore, overallRisk: getRiskLevel(avg),
    extensions, errors,
  }
}

export function formatJson(report: AuditReport): string {
  return JSON.stringify(report, null, 2)
}

export function formatMarkdown(report: AuditReport): string {
  const L: string[] = []
  L.push("# ExtAudit Report\n")
  L.push(`**Generated:** ${report.timestamp}`)
  L.push(`**Target:** ${report.target}`)
  L.push(`**Extensions scanned:** ${report.extensionsScanned}`)
  if (report.extensionsFailed > 0) L.push(`**Failed to parse:** ${report.extensionsFailed}`)
  L.push(`**Total findings:** ${report.totalFindings}`)
  L.push(`**Overall risk:** ${report.overallRisk}\n`)

  L.push("## Severity Breakdown\n")
  L.push("| Severity | Count |")
  L.push("|----------|------:|")
  L.push(`| Critical | ${report.severityCounts.critical} |`)
  L.push(`| High     | ${report.severityCounts.high} |`)
  L.push(`| Medium   | ${report.severityCounts.medium} |`)
  L.push(`| Low      | ${report.severityCounts.low} |\n`)

  if (report.errors.length) {
    L.push("## Errors\n")
    for (const e of report.errors) L.push(`- ${e}`)
    L.push("")
  }

  L.push("## Extension Details\n")
  for (const ext of report.extensions) {
    L.push(`### ${emoji(ext.riskLevel)} ${ext.manifest.displayName||ext.manifest.name} (${ext.manifest.version}) — Score: ${ext.score} [${ext.riskLevel}]\n`)
    if (ext.manifest.publisher) L.push(`- **Publisher:** ${ext.manifest.publisher}`)
    if (ext.manifest.description) L.push(`- **Description:** ${ext.manifest.description}`)
    L.push(`- **Path:** ${ext.manifest.directory}\n`)
    if (ext.findings.length > 0) {
      L.push("**Findings:**\n")
      for (const f of ext.findings) {
        L.push(`- [${f.severity.toUpperCase()}] **${f.ruleName}**: ${f.message}`)
        if (f.evidence) L.push(`  - Evidence: \`${f.evidence.slice(0,120)}\``)
      }
      L.push("")
    } else {
      L.push("✅ No findings detected.\n")
    }
  }
  L.push("---")
  L.push("_Generated by ExtAudit — https://github.com/rogerchappel/extaudit_")
  return L.join("\n")
}

export function formatSummary(report: AuditReport): string {
  const L: string[] = []
  L.push("extaudit — Extension Manifest Auditor")
  L.push("======================================\n")
  L.push(`Target: ${report.target}`)
  L.push(`Scanned: ${report.extensionsScanned} extension${report.extensionsScanned===1?"":"s"}`)
  if (report.extensionsFailed) L.push(`Failed: ${report.extensionsFailed}`)
  L.push(`Overall risk: ${report.overallRisk.toUpperCase()}\n`)
  L.push("Severity summary:")
  Object.entries(report.severityCounts).forEach(([k,v]) =>
    L.push(`  ${k[0].toUpperCase()+k.slice(1)}: ${v}`))
  L.push("")

  const risky = report.extensions.filter(e=>e.score>0).slice(0,10)
  if (risky.length) {
    L.push("Top findings:")
    for (const ext of risky) {
      L.push(`  ${emoji(ext.riskLevel)} ${ext.manifest.displayName||ext.manifest.name} — score ${ext.score} (${ext.riskLevel})`)
      for (const f of ext.findings.slice(0,3)) {
        L.push(`    ${f.severity.toUpperCase()}: ${f.ruleName} — ${f.message.slice(0,80)}`)
      }
      if (ext.findings.length > 3) L.push(`    ... and ${ext.findings.length-3} more`)
    }
  } else {
    L.push("No findings — all extensions appear clean.")
  }
  L.push("\nRun with --format json for full report data.")
  L.push("Run with --format markdown for shareable Markdown report.")
  return L.join("\n")
}

function emoji(level: string): string {
  switch (level) {
    case "safe": return "✅"
    case "caution": return "⚠️"
    case "suspicious": return "🚨"
    case "dangerous": return "🔴"
    default: return "❓"
  }
}
